[tool.dojo.world]
name = "Underdark"
description = "A generative, on-chain 3D skin-crawler. Something ill under Kurnkornor stirs, down those crumbling old manor stairs. Beware the fading light, and your fraying sanity. Most of all, beware the gibbering of the Slender Duck!"
icon_uri = "https://underdark.vercel.app/images/logo.jpg"
cover_uri = "https://underdark.vercel.app/images/splash.jpg"
website = "https://underdark-splash.vercel.app"
socials.x = "https://twitter.com/lootunderworld"

[package]
cairo-version = "2.3.0"
name = "underdark"
version = "0.2.1"

[cairo]
sierra-replace-ids = true

[dependencies]
# dojo = { git = "https://github.com/dojoengine/dojo.git", rev = "47c0cbcfa4ebd4d4b504ec959fdbcfd3e4271e8a" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.5" }


[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
world_address = "0x7006ea4fd2de52944def100605e48ba82b8c4d15a6bd5ef04fbc579d8b00076"

# Development
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# SLOT
# rpc_url = "https://api.cartridge.gg/x/underdark/katana"
# account_address = "0x4e9c35bb113eaf274457edb2473437b02fe636f14c477aa110ba8d3626d3282"
# private_key = "0x45250d2d14c52cd1a7ad81e91d89550630ae90a3398ebf836bed3dcebc0cec3"
